import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import i18next from 'i18next';

interface Member {
  user_id: string;
  role: string;
  profiles?: { first_name?: string; avatar_color?: string };
}

interface Transaction {
  id: string;
  user_id: string;
  amount: number;
  created_at: string;
  status: string;
}

interface Withdrawal {
  id: string;
  user_id: string;
  amount: number;
  total_deducted?: number;
  created_at: string;
  status: string;
  note?: string;
}

interface Expense {
  withdrawal_id: string;
  name: string;
  amount: number;
}

interface Pot {
  name: string;
  created_at: string;
  balance: number;
  goal_amount?: number | null;
  currency: string;
}

const translations: Record<string, Record<string, string>> = {
  en: {
    reportSubtitle: 'Pot Activity Report',
    potSummary: 'Pot Summary',
    potName: 'Pot Name',
    created: 'Created',
    targetAmount: 'Initial Amount',
    noGoal: 'No initial amount set',
    currentBalance: 'Current Balance',
    totalFundsAdded: 'Total Funds Added',
    totalWithdrawn: 'Total Withdrawn',
    members: 'Members',
    memberBreakdown: 'Member Breakdown',
    name: 'Name',
    role: 'Role',
    totalAdded: 'Total Added',
    withdrawals: 'Withdrawals',
    withdrawalHistory: 'Withdrawal History',
    member: 'Member',
    date: 'Date',
    deductedFromPot: 'Deducted from pot',
    receivedByMember: 'Received by member',
    expenses: 'Expenses',
    justified: 'Justified',
    none: 'None',
    noApprovedWithdrawals: 'No approved withdrawals yet.',
    generatedBy: 'Generated by Monto on',
    page: 'Page',
    of: 'of',
    roleCreator: 'Creator',
    roleLeader: 'Leader',
    roleMember: 'Member',
  },
  fr: {
    reportSubtitle: "Rapport d'activité du pot",
    potSummary: 'Résumé du pot',
    potName: 'Nom du pot',
    created: 'Créé le',
    targetAmount: 'Montant initial',
    noGoal: 'Aucun montant initial défini',
    currentBalance: 'Solde actuel',
    totalFundsAdded: 'Total des fonds ajoutés',
    totalWithdrawn: 'Total retiré',
    members: 'Membres',
    memberBreakdown: 'Détail par membre',
    name: 'Nom',
    role: 'Rôle',
    totalAdded: 'Total ajouté',
    withdrawals: 'Retraits',
    withdrawalHistory: 'Historique des retraits',
    member: 'Membre',
    date: 'Date',
    deductedFromPot: 'Déduit du pot',
    receivedByMember: 'Reçu par le membre',
    expenses: 'Dépenses',
    justified: 'Justifié',
    none: 'Aucune',
    noApprovedWithdrawals: 'Aucun retrait approuvé pour le moment.',
    generatedBy: 'Généré par Monto le',
    page: 'Page',
    of: 'sur',
    roleCreator: 'Créateur',
    roleLeader: 'Leader',
    roleMember: 'Membre',
  },
  de: {
    reportSubtitle: 'Aktivitätsbericht des Topfes',
    potSummary: 'Topf-Zusammenfassung',
    potName: 'Topfname',
    created: 'Erstellt am',
    targetAmount: 'Zielbetrag',
    noGoal: 'Kein Ziel gesetzt',
    currentBalance: 'Aktueller Saldo',
    totalFundsAdded: 'Gesamteinzahlungen',
    totalWithdrawn: 'Gesamt abgehoben',
    members: 'Mitglieder',
    memberBreakdown: 'Aufschlüsselung nach Mitglied',
    name: 'Name',
    role: 'Rolle',
    totalAdded: 'Gesamt eingezahlt',
    withdrawals: 'Abhebungen',
    withdrawalHistory: 'Abhebungsverlauf',
    member: 'Mitglied',
    date: 'Datum',
    deductedFromPot: 'Vom Topf abgezogen',
    receivedByMember: 'Vom Mitglied erhalten',
    expenses: 'Ausgaben',
    justified: 'Begründet',
    none: 'Keine',
    noApprovedWithdrawals: 'Noch keine genehmigten Abhebungen.',
    generatedBy: 'Erstellt von Monto am',
    page: 'Seite',
    of: 'von',
    roleCreator: 'Ersteller',
    roleLeader: 'Leiter',
    roleMember: 'Mitglied',
  },
  es: {
    reportSubtitle: 'Informe de actividad del bote',
    potSummary: 'Resumen del bote',
    potName: 'Nombre del bote',
    created: 'Creado el',
    targetAmount: 'Monto objetivo',
    noGoal: 'Sin objetivo definido',
    currentBalance: 'Saldo actual',
    totalFundsAdded: 'Total de fondos añadidos',
    totalWithdrawn: 'Total retirado',
    members: 'Miembros',
    memberBreakdown: 'Desglose por miembro',
    name: 'Nombre',
    role: 'Rol',
    totalAdded: 'Total añadido',
    withdrawals: 'Retiros',
    withdrawalHistory: 'Historial de retiros',
    member: 'Miembro',
    date: 'Fecha',
    deductedFromPot: 'Deducido del bote',
    receivedByMember: 'Recibido por el miembro',
    expenses: 'Gastos',
    justified: 'Justificado',
    none: 'Ninguno',
    noApprovedWithdrawals: 'Aún no hay retiros aprobados.',
    generatedBy: 'Generado por Monto el',
    page: 'Página',
    of: 'de',
    roleCreator: 'Creador',
    roleLeader: 'Líder',
    roleMember: 'Miembro',
  },
};

function getDateLocale(lang: string): string {
  const map: Record<string, string> = { en: 'en-IE', fr: 'fr-FR', de: 'de-DE', es: 'es-ES' };
  return map[lang] || 'en-IE';
}

function formatDateForLang(dateStr: string, lang: string): string {
  const d = new Date(dateStr);
  const locale = getDateLocale(lang);
  if (lang === 'de') {
    return d.toLocaleDateString('de-DE', { day: '2-digit', month: '2-digit', year: 'numeric' });
  }
  if (lang === 'es') {
    const dd = String(d.getDate()).padStart(2, '0');
    const mm = String(d.getMonth() + 1).padStart(2, '0');
    return `${dd}/${mm}/${d.getFullYear()}`;
  }
  // EN and FR: DD Month YYYY
  return d.toLocaleDateString(locale, { day: 'numeric', month: 'long', year: 'numeric' });
}

export function generatePotReport(
  pot: Pot,
  members: Member[],
  transactions: Transaction[],
  withdrawals: Withdrawal[],
  expenses: Expense[],
) {
  const lang = (i18next.language || 'en').slice(0, 2);
  const t = translations[lang] || translations.en;
  const locale = getDateLocale(lang);

  const doc = new jsPDF();
  const currency = pot.currency || 'EUR';
  const fmt = (n: number) => {
    const formatted = new Intl.NumberFormat(locale, { style: 'currency', currency, minimumFractionDigits: 2 }).format(n);
    return formatted.replace(/^([^\d\s-]+)(\d)/, '$1 $2').replace(/^([^\d\s-]+)(-)/, '$1 $2');
  };
  const dateStr = (s: string) => formatDateForLang(s, lang);

  const translateRole = (role: string) => {
    const key = `role${role.charAt(0).toUpperCase()}${role.slice(1)}` as keyof typeof t;
    return t[key] || role.charAt(0).toUpperCase() + role.slice(1);
  };

  const primaryColor: [number, number, number] = [37, 99, 235];
  const darkText: [number, number, number] = [30, 41, 59];
  const mutedText: [number, number, number] = [100, 116, 139];

  let y = 20;

  // Header
  doc.setFontSize(22);
  doc.setTextColor(...primaryColor);
  doc.setFont('helvetica', 'bold');
  doc.text('Monto', 14, y);
  doc.setFontSize(10);
  doc.setTextColor(...mutedText);
  doc.setFont('helvetica', 'normal');
  doc.text(t.reportSubtitle, 55, y);
  y += 4;
  doc.setDrawColor(...primaryColor);
  doc.setLineWidth(0.5);
  doc.line(14, y, 196, y);
  y += 12;

  // Pot Summary
  doc.setFontSize(14);
  doc.setTextColor(...darkText);
  doc.setFont('helvetica', 'bold');
  doc.text(t.potSummary, 14, y);
  y += 8;

  const completedDeposits = transactions.filter(t => Number(t.amount) > 0 && t.status === 'completed');
  const totalAdded = completedDeposits.reduce((s, t) => s + Number(t.amount), 0);
  const approvedWithdrawals = withdrawals.filter(w => w.status === 'approved');
  const totalWithdrawn = approvedWithdrawals.reduce((s, w) => s + Number(w.total_deducted || w.amount), 0);

  const summaryData = [
    [t.potName, pot.name],
    [t.created, dateStr(pot.created_at)],
    [t.targetAmount, pot.goal_amount ? fmt(pot.goal_amount) : t.noGoal],
    [t.currentBalance, fmt(pot.balance)],
    [t.totalFundsAdded, fmt(totalAdded)],
    [t.totalWithdrawn, fmt(totalWithdrawn)],
    [t.members, String(members.length)],
  ];

  autoTable(doc, {
    startY: y,
    head: [],
    body: summaryData,
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 3, textColor: darkText },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 50 },
      1: { cellWidth: 'auto' },
    },
    margin: { left: 14 },
  });

  y = (doc as any).lastAutoTable.finalY + 14;

  // Member Breakdown
  doc.setFontSize(14);
  doc.setTextColor(...darkText);
  doc.setFont('helvetica', 'bold');
  doc.text(t.memberBreakdown, 14, y);
  y += 2;

  const getName = (userId: string) => {
    const m = members.find(m => m.user_id === userId);
    return (m?.profiles as any)?.first_name || 'Unknown';
  };

  const memberRows = members.map(m => {
    const uid = m.user_id;
    const name = (m.profiles as any)?.first_name || 'Unknown';
    const role = translateRole(m.role);
    const memberDeposits = completedDeposits.filter(t => t.user_id === uid);
    const totalDeposited = memberDeposits.reduce((s, t) => s + Number(t.amount), 0);
    const memberApproved = approvedWithdrawals.filter(w => w.user_id === uid);
    const totalMemberWithdrawn = memberApproved.reduce((s, w) => s + Number(w.total_deducted || w.amount), 0);
    return [name, role, fmt(totalDeposited), String(memberApproved.length), fmt(totalMemberWithdrawn)];
  });

  autoTable(doc, {
    startY: y,
    head: [[t.name, t.role, t.totalAdded, t.withdrawals, t.totalWithdrawn]],
    body: memberRows,
    theme: 'striped',
    headStyles: { fillColor: primaryColor, fontSize: 9, fontStyle: 'bold' },
    styles: { fontSize: 9, cellPadding: 3, textColor: darkText },
    margin: { left: 14 },
  });

  y = (doc as any).lastAutoTable.finalY + 14;

  // Withdrawal History
  if (y > 250) { doc.addPage(); y = 20; }

  doc.setFontSize(14);
  doc.setTextColor(...darkText);
  doc.setFont('helvetica', 'bold');
  doc.text(t.withdrawalHistory, 14, y);
  y += 2;

  const expensesByWithdrawal: Record<string, Expense[]> = {};
  expenses.forEach(e => {
    if (!expensesByWithdrawal[e.withdrawal_id]) expensesByWithdrawal[e.withdrawal_id] = [];
    expensesByWithdrawal[e.withdrawal_id].push(e);
  });

  const withdrawalRows = approvedWithdrawals.map(w => {
    const name = getName(w.user_id);
    const date = dateStr(w.created_at);
    const deducted = Number(w.total_deducted || w.amount);
    const received = Number(w.amount);
    const wExpenses = expensesByWithdrawal[w.id] || [];
    const expenseList = wExpenses.length > 0
      ? wExpenses.map(e => `${e.name} — ${fmt(e.amount)}`).join('\n')
      : t.none;
    const expenseTotal = wExpenses.reduce((s, e) => s + Number(e.amount), 0);
    const justified = wExpenses.length > 0 && deducted > 0
      ? `${Math.min(100, Math.round((expenseTotal / deducted) * 100))}%`
      : '—';
    return [name, date, fmt(deducted), fmt(received), expenseList, justified];
  });

  if (withdrawalRows.length === 0) {
    doc.setFontSize(10);
    doc.setTextColor(...mutedText);
    doc.setFont('helvetica', 'normal');
    doc.text(t.noApprovedWithdrawals, 14, y + 8);
    y += 16;
  } else {
    autoTable(doc, {
      startY: y,
      head: [[t.member, t.date, t.deductedFromPot, t.receivedByMember, t.expenses, t.justified]],
      body: withdrawalRows,
      theme: 'striped',
      headStyles: { fillColor: primaryColor, fontSize: 8, fontStyle: 'bold' },
      styles: { fontSize: 8, cellPadding: 2.5, textColor: darkText, overflow: 'linebreak' },
      columnStyles: { 4: { cellWidth: 50 } },
      margin: { left: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  const footerDate = formatDateForLang(new Date().toISOString(), lang);
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...mutedText);
    doc.text(`${t.generatedBy} ${footerDate}`, 14, 290);
    doc.text(`${t.page} ${i} ${t.of} ${pageCount}`, 180, 290);
  }

  const safeName = pot.name.replace(/[^a-zA-Z0-9]/g, '_');
  const today = new Date().toISOString().slice(0, 10);
  doc.save(`Monto_Report_${safeName}_${today}.pdf`);
}
